### ISSUE TITLE
Error inflating class technolifestyle.com.imageslider.FlipperLayout

### ISSUE THREAD

**Issue by Midhilaj** [therealshabi/AutoImageFlipper#5]
what is this error and how to solve it?<br>  

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                        Caused by: android.view.InflateException: Binary XML file line #30: Binary XML file line #47: Error inflating class technolifestyle.com.imageslider.FlipperLayout
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)

**Comment by hernando-montoya** [comment]
@Midhilaj just add to your build.gradle (app module):
    implementation 'me.relex:circleindicator:1.2.2@aar'

**Comment by Jejid** [comment]
I have same proble but implementation 'me.relex:circleindicator:1.2.2@aar' dont fix it for me

Error:
android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class technolifestyle.com.imageslider.FlipperLayout
Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class technolifestyle.com.imageslider.FlipperLayout

ITS WORKS if i use implementation 'com.github.therealshabi:AutoImageFlipper:v1.4.1' but 1.4.2 and 1.4.3 give me error 

Next my app graddle:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "domicilios.jejid.domiciliosllanos"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 21
        versionName "1.2.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.gms:play-services-maps:11.6.2'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation("com.github.bumptech.glide:glide:4.8.0@aar") {
        exclude group: "com.android.support"
        transitive = true
    }

    implementation 'com.android.support:recyclerview-v7:26.1'
    implementation 'com.android.support:appcompat-v7:26.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'org.jsoup:jsoup:1.8.3'
    testImplementation 'junit:junit:4.12'
    implementation 'com.sun.mail:android-mail:1.5.5'
    implementation 'com.sun.mail:android-activation:1.5.5'
    implementation 'com.github.therealshabi:AutoImageFlipper:v1.4.3'
    implementation 'me.relex:circleindicator:1.2.2@aar'
