### ISSUE TITLE
    java.lang.NoSuchMethodError: No static method get()Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.ebrosys.sujatamastaniagent-1/split_lib_dependencies_apk.apk)

### ISSUE THREAD

**Issue by kiransambare** [therealshabi/AutoImageFlipper#6]
E/art: ----- class 'Lcom/squareup/picasso/Picasso;' cl=0x12c4dea0 -----
      objectSize=568 (440 from super)
      access=0x0000.0001
      super='java.lang.Class<java.lang.Object>' (cl=0x0)
      vtable (29 entries, 11 in super):
         0: boolean com.squareup.picasso.Picasso.areIndicatorsEnabled()
         1: void com.squareup.picasso.Picasso.cancelRequest(android.widget.ImageView)
         2: void com.squareup.picasso.Picasso.cancelRequest(android.widget.RemoteViews, int)
         3: void com.squareup.picasso.Picasso.cancelRequest(com.squareup.picasso.Target)
         4: void com.squareup.picasso.Picasso.cancelTag(java.lang.Object)
         5: void com.squareup.picasso.Picasso.complete(com.squareup.picasso.BitmapHunter)
         6: void com.squareup.picasso.Picasso.defer(android.widget.ImageView, com.squareup.picasso.DeferredRequestCreator)
         7: void com.squareup.picasso.Picasso.enqueueAndSubmit(com.squareup.picasso.Action)
         8: java.util.List com.squareup.picasso.Picasso.getRequestHandlers()
         9: com.squareup.picasso.StatsSnapshot com.squareup.picasso.Picasso.getSnapshot()
        10: void com.squareup.picasso.Picasso.invalidate(android.net.Uri)
        11: void com.squareup.picasso.Picasso.invalidate(java.io.File)
        12: void com.squareup.picasso.Picasso.invalidate(java.lang.String)
        13: boolean com.squareup.picasso.Picasso.isDebugging()
        14: boolean com.squareup.picasso.Picasso.isLoggingEnabled()
        15: com.squareup.picasso.RequestCreator com.squareup.picasso.Picasso.load(int)
        16: com.squareup.picasso.RequestCreator com.squareup.picasso.Picasso.load(android.net.Uri)
        17: com.squareup.picasso.RequestCreator com.squareup.picasso.Picasso.load(java.io.File)
        18: com.squareup.picasso.RequestCreator com.squareup.picasso.Picasso.load(java.lang.String)
        19: void com.squareup.picasso.Picasso.pauseTag(java.lang.Object)
        20: android.graphics.Bitmap com.squareup.picasso.Picasso.quickMemoryCacheCheck(java.lang.String)
        21: void com.squareup.picasso.Picasso.resumeAction(com.squareup.picasso.Action)
        22: void com.squareup.picasso.Picasso.resumeTag(java.lang.Object)
        23: void com.squareup.picasso.Picasso.setDebugging(boolean)
        24: void com.squareup.picasso.Picasso.setIndicatorsEnabled(boolean)
        25: void com.squareup.picasso.Picasso.setLoggingEnabled(boolean)
        26: void com.squareup.picasso.Picasso.shutdown()
        27: void com.squareup.picasso.Picasso.submit(com.squareup.picasso.Action)
        28: com.squareup.picasso.Request com.squareup.picasso.Picasso.transformRequest(com.squareup.picasso.Request)
      direct methods (7 entries):
         0: void com.squareup.picasso.Picasso.<clinit>()
         1: void com.squareup.picasso.Picasso.<init>(android.content.Context, com.squareup.picasso.Dispatcher, com.squareup.picasso.Cache, com.squareup.picasso.Picasso$Listener, com.squareup.picasso.Picasso$RequestTransformer, java.util.List, com.squareup.picasso.Stats, android.graphics.Bitmap$Config, boolean, boolean)
         2: void com.squareup.picasso.Picasso.access$000(com.squareup.picasso.Picasso, java.lang.Object)
         3: void com.squareup.picasso.Picasso.cancelExistingRequest(java.lang.Object)
         4: void com.squareup.picasso.Picasso.deliverAction(android.graphics.Bitmap, com.squareup.picasso.Picasso$LoadedFrom, com.squareup.picasso.Action)
         5: void com.squareup.picasso.Picasso.setSingletonInstance(com.squareup.picasso.Picasso)
         6: com.squareup.picasso.Picasso com.squareup.picasso.Picasso.with(android.content.Context)
      static fields (3 entries):
         0: android.os.Handler com.squareup.picasso.Picasso.HANDLER
         1: java.lang.String com.squareup.picasso.Picasso.TAG
         2: com.squareup.picasso.Picasso com.squareup.picasso.Picasso.singleton
      instance fields (15 entries):
11-22 12:11:52.527 12828-12828/com.ebrosys.sujatamastaniagent E/art:      0: com.squareup.picasso.Cache com.squareup.picasso.Picasso.cache
         1: com.squareup.picasso.Picasso$CleanupThread com.squareup.picasso.Picasso.cleanupThread
         2: android.content.Context com.squareup.picasso.Picasso.context
         3: android.graphics.Bitmap$Config com.squareup.picasso.Picasso.defaultBitmapConfig
         4: com.squareup.picasso.Dispatcher com.squareup.picasso.Picasso.dispatcher
         5: boolean com.squareup.picasso.Picasso.indicatorsEnabled
         6: com.squareup.picasso.Picasso$Listener com.squareup.picasso.Picasso.listener
         7: boolean com.squareup.picasso.Picasso.loggingEnabled
         8: java.lang.ref.ReferenceQueue com.squareup.picasso.Picasso.referenceQueue
         9: java.util.List com.squareup.picasso.Picasso.requestHandlers
        10: com.squareup.picasso.Picasso$RequestTransformer com.squareup.picasso.Picasso.requestTransformer
        11: boolean com.squareup.picasso.Picasso.shutdown
        12: com.squareup.picasso.Stats com.squareup.picasso.Picasso.stats
        13: java.util.Map com.squareup.picasso.Picasso.targetToAction
        14: java.util.Map com.squareup.picasso.Picasso.targetToDeferredRequestCreator
11-22 12:11:52.528 12828-12828/com.ebrosys.sujatamastaniagent E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ebrosys.sujatamastaniagent, PID: 12828
    java.lang.NoSuchMethodError: No static method get()Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.ebrosys.sujatamastaniagent-1/split_lib_dependencies_apk.apk)
        at technolifestyle.com.imageslider.FlipperView.bindData(FlipperView.java:109)
        at technolifestyle.com.imageslider.FlipperView.getView(FlipperView.java:87)
        at technolifestyle.com.imageslider.FlipperAdapter.instantiateItem(FlipperAdapter.java:56)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1086)
        at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
        at technolifestyle.com.imageslider.FlipperAdapter.addFlipperView(FlipperAdapter.java:27)
        at technolifestyle.com.imageslider.FlipperLayout.addFlipperView(FlipperLayout.java:131)
        at com.ebrosys.sujatamastaniagent.Activity.TypesActivity.setSliderViews(TypesActivity.java:301)
        at com.ebrosys.sujatamastaniagent.Activity.TypesActivity.access$000(TypesActivity.java:59)
        at com.ebrosys.sujatamastaniagent.Activity.TypesActivity$3.onResponse(TypesActivity.java:243)
        at com.ebrosys.sujatamastaniagent.Activity.TypesActivity$3.onResponse(TypesActivity.java:218)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:78)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5468)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)

**Comment by therealshabi** [comment]
What's this? You should have at least specified when and where this error is coming from or what was this all about, these logs would have made more sense had there been an apt description for it
